### ISSUE TITLE
HELP: unexpected value

### ISSUE THREAD

**Issue by tfhappy** [shopspring/decimal#143]
```
func TestDecimalDivMul(t *testing.T) {
	a := decimal.New(1, 0)
	b := decimal.New(3, 0)
	c := a.Div(b).Mul(b)

	equal := c.Equal(a)
	if !equal {
		t.Errorf("expected %s, got %s", a.String(), c.String())
	}
}
//  expected 1, got 0.9999999999999999
```

**Comment by leighmcculloch** [comment]
I think this is because this library according to it's readme supports `arbitrary-precision fixed-point decimal numbers` `with a maximum of 2^31 digits after the decimal point`. I _think_ if you needed to be able to preserve the rational completely you might be able to use Go's stdlib `big.Rat`, but personally I find it difficult to use correctly.

An example for how you might write your code above using `big.Rat`:
```go
a := big.NewRat(1, 1)
b := big.NewRat(3, 1)
	
c := &big.Rat{}
c.Quo(a, b)
fmt.Println(c.FloatString(7))
// Output:
// 0.3333333
	
d := &big.Rat{}
d.Mul(c, b)
fmt.Println(d.FloatString(7))
// Output:
// 1.0000000
```
https://play.golang.org/p/A9uAZ62jv42

**Comment by tfhappy** [comment]
thanks
