### ISSUE TITLE
Why 10000.Div(0.001436).Mul(0.001436) != 10000 ?

### ISSUE THREAD

**Issue by nifflerfox** [shopspring/decimal#155]
```
package main

import (
	"fmt"
	"github.com/shopspring/decimal"
)

func main()  {
	a, _ := decimal.NewFromString("10000")
	b, _ := decimal.NewFromString("0.001436")
	fmt.Println(a.Div(b).Mul(b)) // 10000.0000000000000000000308
}
```

What's going on?

**Comment by mwoss** [comment]
Thanks, @nifflerfox for pointing this issue. This looks like an incorrect behavior. We will try to fix this as soon as possible.

**Comment by mwoss** [comment]
Sorry, @nifflerfox I think I mislead you. This is indeed correct behavior. 
`Div` method uses a predefined precision parameter, set to 16. So, `a.Div(b)` operation returns the result with an accuracy of 16 decimal places. (btw. API provides `DivRound` method where you can set precision parameter).
The result of the 10 / 0.001436 operation is an irrational number that cannot be represented using finite precision. That's why the result is not exact 10.0. 
I've done some research about it and the most common and probably the right way of handling such a situation is to round the result of the operation. `a.Div(b)` and `a.Div(b).Mul(b)` should return decimal with identical precision. 
Any thoughts?

**Comment by shawnwyckoff** [comment]
I see, you are right, thanks a lot :)

**Comment by nifflerfox** [comment]
hi @mwoss , I think there is some thing wrong in this demo, default precision is 16 right? but why a.Div(b).Mul(b)).String got 10000.0000000000000000000308? precision of this number is 22.

**Comment by mwoss** [comment]
Result of the operation `a.Div(b)` is a decimal with a maximum of 16 digits after a decimal point (by default) `a.Div(b) // 6963788.3008356545961003`. Mul operation doesn't have that restriction it can return a decimal with up to 32 digits after a decimal place. That's why the `a.Div(b).Mul(b))` operation returns `10000.0000000000000000000308`

**Comment by mwoss** [comment]
I think this issue is resolved, as @nifflerfox is not responding, closing.
