### ISSUE TITLE
Export RoundUp/RoundDown method

### ISSUE THREAD

**Issue by lovung** [shopspring/decimal#191]
We only have `Round` method at https://github.com/shopspring/decimal/blob/480f653de814fa150609ed4ef7594a9874555f42/decimal.go#L792-L819

How about exposing the `RoundDown` and `RoundUp` method?

**Comment by njason** [comment]
There are [Floor](https://github.com/shopspring/decimal/blob/13425bb201a7ba7a43911be7995d3571c872f704/decimal.go#L940) and [Ceil](https://github.com/shopspring/decimal/blob/13425bb201a7ba7a43911be7995d3571c872f704/decimal.go#L957), but that only rounds to integer values. Since adding optional parameters to these functions is not an option, I think it would make sense to add these new proposed functions. Added to backlog.

**Comment by mwoss** [comment]
Closing, implemented in #196 and merged to master.
